version: '3.5'

networks:
  network:
    driver: overlay 

services:

  frontend:
    image: eight_puzzle:1.0
    deploy:
      replicas: 1
    ports:
      - "2000:80" 
    networks:
      - network
