networks:
  network:
    driver: bridge

services:

  small_games:
    image: small_games:latest
    container_name: small_games
    build:
      context: .
    ports:
      - "2000:80"
    networks:
      - network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/www.danilocatone.com.cer:/etc/nginx/www.danilocatone.com.cer
      - ./nginx/www.danilocatone.com.key:/etc/nginx/www.danilocatone.com.key
