version: '3.8'

networks:
  network:
    driver: bridge

services:

  eight_puzzle:
    image: eight_puzzle:latest
    container_name: eight_puzzle
    build:
      context: .
    ports:
      - "2000:80"
    networks:
      - network